num_epochs: 10
num_workers: 4
val_ratio: 0.1
test_ratio: 0.1
step_size: 7
gamma: 0.1
mode: train
beam_width: 3
save_model: true
load_model: false
saved_name: model_checkpoint
save_every: 5
eval_every: 5
model_config:
  model_arch: yolocnn-attn
  yolocnn_embed_size: 512
  yolocnn_num_layers: 6
  yolocnn_num_heads: 8